'use strict';

const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');
const btnOpenModal = document.querySelectorAll('.show-modal');

// modal and overlay hide
const closeModal = function () {
  modal.classList.add('hidden');
  overlay.classList.add('hidden');
};

// modal and overlay unhide
const openModal = function () {
  modal.classList.remove('hidden');
  overlay.classList.remove('hidden');
};

for (let i = 0; i < btnOpenModal.length; i++)
  btnOpenModal[i].addEventListener('click', openModal);

// on-click event EventListener
btnCloseModal.addEventListener('click', closeModal);
overlay.addEventListener('click', closeModal);

// key - press EventListener
document.addEventListener('keydown', function (event) {
  // event is an object generated by JavaScript
  // when any key are pressed or 'keydown' event is happend.
  console.log(event);
  console.log(event.key);

  if (event.key === 'Escape' && !modal.classList.contains('hidden')) {
    closeModal();
  }
});
